server:
  port: 8080

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.7.35:1521:rtlfo20
    username: cmis
    password: cmis

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cmis.export.entity
  configuration:
    map-underscore-to-camel-case: true


    # JWT相关配置
    jwt.header: Authorization
    # 过期时间
    jwt.expiration: 864000
    # 注意有一个空格
    jwt.tokenHead: Bearer
    # wechat Auth
    auth.wechat.sessionHost: https://api.weixin.qq.com/sns/jscode2session
    auth.wechat.appId: ee
    auth.wechat.secret: qq
    auth.wechat.grantType: authorization_code