server:
  port: 8080

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.7.156:1521:rtlfo30
    username: cmis
    password: cmis

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cmis.export.entity
  configuration:
    map-underscore-to-camel-case: true